/*
 * Tenzing Microservice
 * Tenzing is a Bosch SoftTec microservice for storing, managing and distributing user trips.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: BSOT_PJ-SC3_Cloud-CF@de.bosch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bosch.softtec.micro.tenzing.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Holds the properties for a POI (Point of Interest). If the properties are set to a GPS point, the point is highlighted as a POI and gets special treatment on the server side.
 */
@ApiModel(description = "Holds the properties for a POI (Point of Interest). If the properties are set to a GPS point, the point is highlighted as a POI and gets special treatment on the server side.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-06T13:30:17.808+01:00[Europe/Berlin]")
public class PoiProperties {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;


  public PoiProperties name(String name) {

    this.name = name;
    return this;
  }

   /**
   * The name of this entry. The given text will be trimmed (leading and trailing spaces will be removed).
   * @return name
  **/
  @ApiModelProperty(example = "Dudhsagar Falls", required = true, value = "The name of this entry. The given text will be trimmed (leading and trailing spaces will be removed).")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public PoiProperties description(String description) {

    this.description = description;
    return this;
  }

   /**
   * The description of this entry. The given text will be trimmed (leading and trailing spaces will be removed).
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "It will be your lifetime experience.", value = "The description of this entry. The given text will be trimmed (leading and trailing spaces will be removed).")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoiProperties poiProperties = (PoiProperties) o;
    return Objects.equals(this.name, poiProperties.name) &&
        Objects.equals(this.description, poiProperties.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoiProperties {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

