/*
 * Tenzing Microservice
 * Tenzing is a Bosch SoftTec microservice for storing, managing and distributing user trips.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: BSOT_PJ-SC3_Cloud-CF@de.bosch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bosch.softtec.micro.tenzing.client.model;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Represents a trip object with which only contains metadata about a trip. The GPS track and directions are not included.
 */
@ApiModel(description = "Represents a trip object with which only contains metadata about a trip. The GPS track and directions are not included.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-06T13:30:17.808+01:00[Europe/Berlin]")
public class TripMetadata {
  public static final String SERIALIZED_NAME_TRIP_ID = "tripId";
  @SerializedName(SERIALIZED_NAME_TRIP_ID)
  private String tripId;

  public static final String SERIALIZED_NAME_VISIBILITY = "visibility";
  @SerializedName(SERIALIZED_NAME_VISIBILITY)
  private VisibilityType visibility;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  private String owner;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_MODIFIED = "modified";
  @SerializedName(SERIALIZED_NAME_MODIFIED)
  private OffsetDateTime modified;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private List<Link> links = null;


  public TripMetadata tripId(String tripId) {

    this.tripId = tripId;
    return this;
  }

   /**
   * The unique identifier of an entity.
   * @return tripId
  **/
  @ApiModelProperty(example = "5da983bef8e66a36e1f4ce2c", required = true, value = "The unique identifier of an entity.")

  public String getTripId() {
    return tripId;
  }


  public void setTripId(String tripId) {
    this.tripId = tripId;
  }


  public TripMetadata visibility(VisibilityType visibility) {

    this.visibility = visibility;
    return this;
  }

   /**
   * Get visibility
   * @return visibility
  **/
  @ApiModelProperty(required = true, value = "")

  public VisibilityType getVisibility() {
    return visibility;
  }


  public void setVisibility(VisibilityType visibility) {
    this.visibility = visibility;
  }


  public TripMetadata name(String name) {

    this.name = name;
    return this;
  }

   /**
   * The name of this entry. The given text will be trimmed (leading and trailing spaces will be removed).
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Dudhsagar Falls", value = "The name of this entry. The given text will be trimmed (leading and trailing spaces will be removed).")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public TripMetadata description(String description) {

    this.description = description;
    return this;
  }

   /**
   * The description of this entry. The given text will be trimmed (leading and trailing spaces will be removed).
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "It will be your lifetime experience.", value = "The description of this entry. The given text will be trimmed (leading and trailing spaces will be removed).")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public TripMetadata owner(String owner) {

    this.owner = owner;
    return this;
  }

   /**
   * The id of the user that is the owner/author of this trip.
   * @return owner
  **/
  @ApiModelProperty(example = "tenzing", required = true, value = "The id of the user that is the owner/author of this trip.")

  public String getOwner() {
    return owner;
  }


  public void setOwner(String owner) {
    this.owner = owner;
  }


  public TripMetadata created(OffsetDateTime created) {

    this.created = created;
    return this;
  }

   /**
   * The point in UTC time this trip was created, in milliseconds since January 1, 1970.
   * @return created
  **/
  @ApiModelProperty(example = "2019-05-15T11:17:21Z", required = true, value = "The point in UTC time this trip was created, in milliseconds since January 1, 1970.")

  public OffsetDateTime getCreated() {
    return created;
  }


  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public TripMetadata modified(OffsetDateTime modified) {

    this.modified = modified;
    return this;
  }

   /**
   * The point in UTC time this trip was modified, in milliseconds since January 1, 1970.
   * @return modified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-05-18T10:17:21Z", value = "The point in UTC time this trip was modified, in milliseconds since January 1, 1970.")

  public OffsetDateTime getModified() {
    return modified;
  }


  public void setModified(OffsetDateTime modified) {
    this.modified = modified;
  }


  public TripMetadata links(List<Link> links) {

    this.links = links;
    return this;
  }

  public TripMetadata addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Link>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Contains the links of all resources of this entity. If available, images are linked to the trip. At a minimum, however, there is a link to the trip entity itself.
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Contains the links of all resources of this entity. If available, images are linked to the trip. At a minimum, however, there is a link to the trip entity itself.")

  public List<Link> getLinks() {
    return links;
  }


  public void setLinks(List<Link> links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripMetadata tripMetadata = (TripMetadata) o;
    return Objects.equals(this.tripId, tripMetadata.tripId) &&
        Objects.equals(this.visibility, tripMetadata.visibility) &&
        Objects.equals(this.name, tripMetadata.name) &&
        Objects.equals(this.description, tripMetadata.description) &&
        Objects.equals(this.owner, tripMetadata.owner) &&
        Objects.equals(this.created, tripMetadata.created) &&
        Objects.equals(this.modified, tripMetadata.modified) &&
        Objects.equals(this.links, tripMetadata.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tripId, visibility, name, description, owner, created, modified, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripMetadata {\n");
    sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

