/*
 * Tenzing Microservice
 * Tenzing is a Bosch SoftTec microservice for storing, managing and distributing user trips.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: BSOT_PJ-SC3_Cloud-CF@de.bosch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bosch.softtec.micro.tenzing.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Represents the (body) data of an user trip without server-side metadata.
 */
@ApiModel(description = "Represents the (body) data of an user trip without server-side metadata.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-06T13:30:17.808+01:00[Europe/Berlin]")
public class TripBody {
  public static final String SERIALIZED_NAME_VISIBILITY = "visibility";
  @SerializedName(SERIALIZED_NAME_VISIBILITY)
  private VisibilityType visibility;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_TRACK = "track";
  @SerializedName(SERIALIZED_NAME_TRACK)
  private List<GpsPoint> track = new ArrayList<GpsPoint>();

  public static final String SERIALIZED_NAME_DIRECTIONS = "directions";
  @SerializedName(SERIALIZED_NAME_DIRECTIONS)
  private List<GpsPoint> directions = new ArrayList<GpsPoint>();


  public TripBody visibility(VisibilityType visibility) {

    this.visibility = visibility;
    return this;
  }

   /**
   * Get visibility
   * @return visibility
  **/
  @ApiModelProperty(required = true, value = "")

  public VisibilityType getVisibility() {
    return visibility;
  }


  public void setVisibility(VisibilityType visibility) {
    this.visibility = visibility;
  }


  public TripBody name(String name) {

    this.name = name;
    return this;
  }

   /**
   * The name of this entry. The given text will be trimmed (leading and trailing spaces will be removed).
   * @return name
  **/
  @ApiModelProperty(example = "Dudhsagar Falls", required = true, value = "The name of this entry. The given text will be trimmed (leading and trailing spaces will be removed).")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public TripBody description(String description) {

    this.description = description;
    return this;
  }

   /**
   * The description of this entry. The given text will be trimmed (leading and trailing spaces will be removed).
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "It will be your lifetime experience.", value = "The description of this entry. The given text will be trimmed (leading and trailing spaces will be removed).")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public TripBody track(List<GpsPoint> track) {

    this.track = track;
    return this;
  }

  public TripBody addTrackItem(GpsPoint trackItem) {
    this.track.add(trackItem);
    return this;
  }

   /**
   * A list of all GPS points representing the track of this trip.
   * @return track
  **/
  @ApiModelProperty(required = true, value = "A list of all GPS points representing the track of this trip.")

  public List<GpsPoint> getTrack() {
    return track;
  }


  public void setTrack(List<GpsPoint> track) {
    this.track = track;
  }


  public TripBody directions(List<GpsPoint> directions) {

    this.directions = directions;
    return this;
  }

  public TripBody addDirectionsItem(GpsPoint directionsItem) {
    this.directions.add(directionsItem);
    return this;
  }

   /**
   * A list of all GPS points representing crucial directional changes.
   * @return directions
  **/
  @ApiModelProperty(required = true, value = "A list of all GPS points representing crucial directional changes.")

  public List<GpsPoint> getDirections() {
    return directions;
  }


  public void setDirections(List<GpsPoint> directions) {
    this.directions = directions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripBody tripBody = (TripBody) o;
    return Objects.equals(this.visibility, tripBody.visibility) &&
        Objects.equals(this.name, tripBody.name) &&
        Objects.equals(this.description, tripBody.description) &&
        Objects.equals(this.track, tripBody.track) &&
        Objects.equals(this.directions, tripBody.directions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(visibility, name, description, track, directions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripBody {\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    track: ").append(toIndentedString(track)).append("\n");
    sb.append("    directions: ").append(toIndentedString(directions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

